version: '3.8'

services:
  db:
      image: postgres:14
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: internship_app
        INTERNSHIP_APP_DATABASE_PASSWORD: password
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/internship_app
      POSTGRES_PASSWORD: password
      INTERNSHIP_APP_DATABASE_PASSWORD: password
      SECRET_KEY_BASE: 32ab7a11178772d4f27133e671986bc82554f0714074113c06219f754c8f78ecd16f80c34ffc5b584c491641117072a625f0e1ecee90d21e5a0241008616e27e


    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    
volumes:
  pg_data:
