
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  database: internship_app
  port: "5432"
  host: db


development:
  <<: *default
  database: internship_app_development

  
test:
  <<: *default
  database: internship_app_test


production:
  primary: &primary_production
    <<: *default
    database: internship_app_production
    username: postgres
    password: <%= ENV["INTERNSHIP_APP_DATABASE_PASSWORD", "password"] %>
    host: db
  cache:
    <<: *primary_production
    database: internship_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: internship_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: internship_app_production_cable
    migrations_paths: db/cable_migrate